# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geos_test_roundtrip_wkt <- function(wkt) {
    .Call(`_libgeos_geos_test_roundtrip_wkt`, wkt)
}

geos_test_roundtrip_wkb <- function(wkb) {
    .Call(`_libgeos_geos_test_roundtrip_wkb`, wkb)
}

geos_wkt_to_wkb <- function(wkt) {
    .Call(`_libgeos_geos_wkt_to_wkb`, wkt)
}

geos_wkb_to_wkt <- function(wkb) {
    .Call(`_libgeos_geos_wkb_to_wkt`, wkb)
}

geos_wkt_is_parseable <- function(wkt) {
    .Call(`_libgeos_geos_wkt_is_parseable`, wkt)
}

geos_wkb_is_parseable <- function(wkb) {
    .Call(`_libgeos_geos_wkb_is_parseable`, wkb)
}

geos_version_impl <- function() {
    .Call(`_libgeos_geos_version_impl`)
}

geos_test_throw_error <- function() {
    invisible(.Call(`_libgeos_geos_test_throw_error`))
}

intersect_text <- function(input1, input2, precision) {
    .Call(`_libgeos_intersect_text`, input1, input2, precision)
}

intersect_blob <- function(input1, input2, precision) {
    .Call(`_libgeos_intersect_blob`, input1, input2, precision)
}

